export const GET_AUTHENTICATED_USER_SUCCESS = "GET_AUTHENTICATED_USER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";