// API
export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

// Users
export const GET_AUTHENTICATED_USER_SUCCESS = "GET_AUTHENTICATED_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

// Projects
export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";

// Trades
export const ADD_TRADE_SUCCESS = "ADD_TRADE_SUCCESS";
export const GET_TRADES_SUCCESS = "GET_TRADES_SUCCESS";
export const GET_TRADE_SUCCESS = "GET_TRADE_SUCCESS";
export const UPDATE_TRADE_SUCCESS = "UPDATE_TRADE_SUCCESS";
export const DELETE_TRADE_SUCCESS = "DELETE_TRADE_SUCCESS";